### ISSUE TITLE
ImportError: DLL load failed: (problem importing srwlpy)

### ISSUE THREAD

**Issue by SergioLordano** [oasys-kit/oasys-installation-scripts#20]
Hi Luca,

Since one or two months ago, all of our fresh windows installations are not being capable of importing SRW. Therefore, all SRW-related widgets do not appear. The cmd output is the following:

```
Error importing 'orangecontrib.srw.menu.ow_srw_tools_menu'
Traceback (most recent call last):
  File "C:\Users\Sergio\Miniconda3\lib\site-packages\oasys\canvas\discovery.py", line 36, in omenus_from_package
    menu_module = discovery.asmodule(name)
  File "C:\Users\Sergio\Miniconda3\lib\site-packages\orangecanvas\registry\discovery.py", line 505, in asmodule
    return __import__(module, fromlist=[""])
  File "C:\Users\Sergio\AppData\Roaming\Python\Python37\site-packages\orangecontrib\srw\menu\ow_srw_tools_menu.py", line 7, in <module>
    from wofrysrw.propagator.propagators2D.srw_fresnel_native import SRW_APPLICATION
  File "C:\Users\Sergio\AppData\Roaming\Python\Python37\site-packages\wofrysrw\propagator\propagators2D\srw_fresnel_native.py", line 7, in <module>
    from wofrysrw.beamline.srw_beamline import Where
  File "C:\Users\Sergio\AppData\Roaming\Python\Python37\site-packages\wofrysrw\beamline\srw_beamline.py", line 5, in <module>
    from wofrysrw.beamline.optical_elements.srw_optical_element import SRWOpticalElementDisplacement
  File "C:\Users\Sergio\AppData\Roaming\Python\Python37\site-packages\wofrysrw\beamline\optical_elements\srw_optical_element.py", line 7, in <module>
    from wofrysrw.propagator.wavefront2D.srw_wavefront import WavefrontPropagationParameters, WavefrontPropagationOptionalParameters
  File "C:\Users\Sergio\AppData\Roaming\Python\Python37\site-packages\wofrysrw\propagator\wavefront2D\srw_wavefront.py", line 1, in <module>
    from oasys_srw.srwlib import srwl, SRWLWfr, SRWLRadMesh, SRWLStokes, array as srw_array
  File "C:\Users\Sergio\AppData\Roaming\Python\Python37\site-packages\oasys_srw\srwlib.py", line 6, in <module>
    import srwlpy as srwl
ImportError: DLL load failed: Não foi possível encontrar o módulo especificado.
```

I tryed a few things, including copying the `srwlpy.pyd` file to `site-packages` and other folders in the `PYTHONPATH`, but it still can't import. It mentions some DLL, have you or anyone else seen this issue?

**Comment by lucarebuffi** [comment]
I believe there is some issue with pip. We need to add the installation of the SRW library during the OASYS installation, even if I don't like it.

Other users had the same issue, you just have to manually reinstall it:

- open a miniconda3 prompt (Start Menu->Anaconda3 (64 bit)->Anaconda Prompt (Miniconda3)
- type: python -m pip uninstall oasys-srwpy (then answer y)
- do it again to make sure it is actually uninstalled
- type: python -m pip install oasys-srwpy --upgrade

**Comment by lucarebuffi** [comment]
I honestly have no idea what is the issue.

**Comment by SergioLordano** [comment]
Worked fine for me, thank you for the quick answer and for the latest developments!  
Indeed it is a weird issue.. I don't see how it can not import it if the .pyd is in the PYTHONPATH.

**Comment by SergioLordano** [comment]
Bernd just noticed that XRayServer widgets don't appear. They don't appear for me either, but I guess this is unrelated.

**Comment by lucarebuffi** [comment]
it is unrelated, unless pip is not installing anymore the dependent libraries

**Comment by lucarebuffi** [comment]
Try the same trick with its inner library: 

open a miniconda3 prompt (Start Menu->Anaconda3 (64 bit)->Anaconda Prompt (Miniconda3)
type: python -m pip uninstall PyQtWebEngine (then answer y)
do it again to make sure it is actually uninstalled
type: python -m pip install PyQtWebEngine==5.14

**Comment by lucarebuffi** [comment]
type: python -m pip install PyQtWebEngine==5.15.2

**Comment by SergioLordano** [comment]
Great, the trick fixes the issue! Thank you once more!

**Comment by lucarebuffi** [comment]
The issue should be resolved completely with the last release of the installation scripts
