### ISSUE TITLE
Failed Installing Oasys

### ISSUE THREAD

**Issue by NathanAdelaide** [oasys-kit/oasys-installation-scripts#24]
Hi, I cant seem to install OASYS. have tried a few things but cant seem to get past an error perhaps with qmake?
Script log below
Everything seems to run ok until collecting PyQt5 where an error occurs. 

Collecting PyQt5==5.15.2
  Using cached PyQt5-5.15.2.tar.gz (3.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "C:\Code\XRAYModel\Miniconda3\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Code\XRAYModel\Miniconda3\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Code\XRAYModel\Miniconda3\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "C:\Users\nathan\AppData\Local\Temp\pip-build-env-kp5aik6l\overlay\Lib\site-packages\sipbuild\api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "C:\Users\nathan\AppData\Local\Temp\pip-build-env-kp5aik6l\overlay\Lib\site-packages\sipbuild\abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "C:\Users\nathan\AppData\Local\Temp\pip-build-env-kp5aik6l\overlay\Lib\site-packages\sipbuild\project.py", line 586, in setup
          self.apply_user_defaults(tool)
        File "C:\Users\nathan\AppData\Local\Temp\pip-install-l9gb68_c\pyqt5_e2cf793c1e7541ccb4f0d806d3aa64c9\project.py", line 63, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\nathan\AppData\Local\Temp\pip-build-env-kp5aik6l\overlay\Lib\site-packages\pyqtbuild\project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\nathan\AppData\Local\Temp\pip-build-env-kp5aik6l\overlay\Lib\site-packages\sipbuild\project.py", line 237, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "C:\Users\nathan\AppData\Local\Temp\pip-build-env-kp5aik6l\overlay\Lib\site-packages\pyqtbuild\builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed 

Any indications of why? or help with this install would be appreciated. 
Thanks

**Comment by lucarebuffi** [comment]
Hi Nathan, please don't try crazy stuff that could make your system messy and fixing things even more difficult.
I never saw that error before, but...welcome to the Microsoft world.....
I see that you have not installed miniconda in the proposed default path, am I correct? you should avoid that.
Do you mind removing the existing miniconda folder and try installing it again leaving paths as the default ones?

If that is not the case, you can contact me privately and we can arrange a zoom call.

**Comment by lucarebuffi** [comment]
Another question, what version of Windows are you using?

**Comment by NathanAdelaide** [comment]
This is the 64 bit win 10 Enterprise. I started with miniconda in default but ran into the white space problem with my organisations 'onedrive' policy. I chose a new location for all based on my desire for a cloud free day.

**Comment by lucarebuffi** [comment]
white space problem? I am not familiar with that. Try update "pip" and "setuptools" first, then you can restart the Oasys installation with the option of keeping the already installed miniconda 


C:\Code\XRAYModel\Miniconda3\bin\python -m pip install pip --upgrade
C:\Code\XRAYModel\Miniconda3\bin\python -m pip install setuptools --upgrade

then restart the Oasys installation script

**Comment by NathanAdelaide** [comment]
I havent got the dir listed above. Do you mean \miniconda3\Library\bin?

**Comment by lucarebuffi** [comment]
wherever the python executable is, sorry I normally work on a Mac.

**Comment by lucarebuffi** [comment]
I think there is an "Anaconda Prompt" in the application Menu. Run that, it will open a terminal in the proper miniconda3 environment. From there you can simply run the commands:

python -m pip install pip --upgrade
python -m pip install setuptools --upgrade

**Comment by lucarebuffi** [comment]
if you are online we can zoom real quick

**Comment by NathanAdelaide** [comment]
Python executable is in the /miniconda3 dir.   How do I contact you?

**Comment by lucarebuffi** [comment]
https://us06web.zoom.us/j/5151892993?pwd=dk9YWlcxbWJ1bWdOclorSHhyM0dBZz09

Meeting ID: 515 189 2993
Passcode: Dv11MC
